# Generated by Django 6.0.3 on 2026-04-28 19:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenZoneAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_space_id', models.IntegerField(db_index=True)),
                ('public_space_name', models.CharField(blank=True, help_text='Snapshot del nombre al momento del registro', max_length=300)),
                ('external_id', models.IntegerField(help_text='ID del polígono en el cronograma PDF de Urbaser', unique=True)),
                ('cycle_days', models.IntegerField(default=11, help_text='Días entre cortes según contrato')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignación de zona verde',
                'verbose_name_plural': 'Asignaciones de zonas verdes',
                'db_table': 'urbaser_green_zone_assignment',
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='SweepingMacroRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('zone_type', models.CharField(choices=[('residential', 'Residencial — comunas'), ('main_roads', 'Vías principales'), ('historic_center', 'Centro histórico'), ('market', 'Plazas de mercado'), ('sunday', 'Servicio dominical')], default='residential', max_length=20)),
                ('communes_text', models.CharField(blank=True, help_text='Ej: "1,2,3,8,9"', max_length=50)),
                ('days_text', models.CharField(blank=True, help_text='Ej: "Lu-Ju", "Lu-Sá", "Domingo"', max_length=50)),
                ('schedule_text', models.CharField(blank=True, help_text='Texto original del horario: "6:00"', max_length=100)),
                ('start_time', models.TimeField(blank=True, help_text='Parseado para comparación numérica en SLA', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Null si no hay fin explícito en el PPS', null=True)),
                ('active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Área de cobertura — null hasta tener polígonos oficiales', null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Macroruta de barrido',
                'verbose_name_plural': 'Macrorutas de barrido',
                'db_table': 'urbaser_sweeping_macroroute',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AspectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Nombre del ícono Lucide. Ej: alert-circle, camera', max_length=50)),
                ('what_is', models.TextField(help_text='Explicación de qué es este problema y cuándo ocurre')),
                ('how_to_evidence', models.TextField(help_text='Cómo el ciudadano puede documentar este problema con fotos')),
                ('response_time', models.CharField(blank=True, help_text='Tiempo de respuesta según contrato. Ej: 24 horas', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.aspect')),
            ],
            options={
                'verbose_name': 'Contenido informativo del aspecto',
                'verbose_name_plural': 'Contenidos informativos de aspectos',
                'db_table': 'urbaser_aspect_content',
            },
        ),
        migrations.CreateModel(
            name='CuttingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('executed', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='infra_servicios_publicos_urbaser.greenzoneassignment')),
            ],
            options={
                'verbose_name': 'Programación de corte',
                'verbose_name_plural': 'Programaciones de corte',
                'db_table': 'urbaser_cutting_schedule',
                'ordering': ['scheduled_date'],
                'unique_together': {('assignment', 'scheduled_date')},
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField()),
                ('intervention_type', models.CharField(choices=[('grass_cut', 'Corte de césped'), ('tree_pruning', 'Poda de árbol')], default='grass_cut', max_length=15)),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='infra_servicios_publicos_urbaser.greenzoneassignment')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='infra_servicios_publicos_urbaser.cuttingschedule')),
            ],
            options={
                'verbose_name': 'Intervención registrada',
                'verbose_name_plural': 'Intervenciones registradas',
                'db_table': 'urbaser_intervention',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Nombre del ícono Lucide. Ej: trash-2, leaf, droplets', max_length=50)),
                ('summary', models.CharField(help_text='Descripción corta visible en el formulario (máx 300 chars)', max_length=300)),
                ('full_description', models.TextField(help_text='Descripción completa del servicio y sus obligaciones contractuales')),
                ('frequency', models.CharField(blank=True, help_text='Ej: Lunes a sábado según macroruta de tu zona', max_length=200)),
                ('citizen_rights', models.TextField(blank=True, help_text='Derechos del ciudadano según el PPS 2024')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.service')),
            ],
            options={
                'verbose_name': 'Contenido informativo del servicio',
                'verbose_name_plural': 'Contenidos informativos de servicios',
                'db_table': 'urbaser_service_content',
            },
        ),
        migrations.CreateModel(
            name='SweepingMicroRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(blank=True, help_text='Del shapefile: VC1, VARIANT, VAP-2', max_length=50)),
                ('neighborhood_id', models.IntegerField(blank=True, null=True)),
                ('neighborhood_name', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('macroroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microroutes', to='infra_servicios_publicos_urbaser.sweepingmacroroute')),
            ],
            options={
                'verbose_name': 'Microruta de barrido',
                'verbose_name_plural': 'Microrutas de barrido',
                'db_table': 'urbaser_sweeping_microroute',
                'ordering': ['macroroute__code'],
            },
        ),
    ]
