# Generated by Django 6.0.3 on 2026-04-28 19:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField()),
                ('service_slug', models.CharField(max_length=100)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('aspect_id', models.IntegerField()),
                ('aspect_slug', models.CharField(blank=True, max_length=100)),
                ('aspect_description', models.CharField(max_length=200)),
                ('commune_id', models.IntegerField(blank=True, null=True)),
                ('commune_name', models.CharField(blank=True, max_length=50)),
                ('neighborhood_id', models.IntegerField(blank=True, null=True)),
                ('neighborhood_name', models.CharField(blank=True, max_length=150)),
                ('is_rural', models.BooleanField(default=False)),
                ('hamlet_name', models.CharField(blank=True, help_text='Nombre de la vereda si is_rural=True', max_length=150)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_source', models.CharField(choices=[('gps', 'GPS automático'), ('manual', 'Pin manual en mapa'), ('centroid', 'Centroide del barrio')], default='gps', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('under_review', 'En revisión'), ('closed', 'Cerrada')], default='received', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Denuncia ciudadana',
                'verbose_name_plural': 'Denuncias ciudadanas',
                'db_table': 'vee_complaint',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_slug'], name='idx_vee_complaint_service'), models.Index(fields=['status'], name='idx_vee_complaint_status'), models.Index(fields=['created_at'], name='idx_vee_complaint_date'), models.Index(fields=['commune_id'], name='idx_vee_complaint_commune')],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaints/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='veeduria.complaint')),
            ],
            options={
                'verbose_name': 'Evidencia fotográfica',
                'verbose_name_plural': 'Evidencias fotográficas',
                'db_table': 'vee_evidence',
            },
        ),
        migrations.CreateModel(
            name='MetricByCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_id', models.IntegerField()),
                ('commune_name', models.CharField(max_length=50)),
                ('service_slug', models.CharField(max_length=100)),
                ('total_complaints', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('total_violations', models.IntegerField(default=0)),
                ('violation_rate', models.FloatField(default=0.0, help_text='Fracción 0.0–1.0. violations / alerts')),
                ('period', models.DateField(help_text='Primer día del mes calculado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica por comuna',
                'verbose_name_plural': 'Métricas por comuna',
                'db_table': 'vee_metric_by_commune',
                'ordering': ['-period', 'commune_id'],
                'indexes': [models.Index(fields=['period', 'service_slug'], name='idx_vee_metric_period')],
                'unique_together': {('commune_id', 'service_slug', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SLAAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.IntegerField(db_index=True)),
                ('service_slug', models.CharField(max_length=100)),
                ('route_type', models.CharField(help_text='Tipo libre por servicio. Ej: urbaser.sweeping_microroute', max_length=50)),
                ('route_id', models.IntegerField()),
                ('route_label', models.CharField(blank=True, help_text='Etiqueta legible para reportes. Ej: código PPS B211', max_length=50)),
                ('violation', models.BooleanField()),
                ('distance_meters', models.FloatField(blank=True, help_text='Distancia en metros entre la denuncia y la ruta', null=True)),
                ('extra_int', models.IntegerField(blank=True, help_text='Campo entero genérico por servicio. Ej: días desde último corte', null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales por servicio. Claves prefijadas por dominio')),
                ('confidence', models.CharField(choices=[('high', 'Alta — coordenada GPS'), ('medium', 'Media — pin manual'), ('low', 'Baja — centroide barrio')], default='high', max_length=6)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta SLA',
                'verbose_name_plural': 'Alertas SLA',
                'db_table': 'vee_sla_alert',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['complaint_id'], name='idx_vee_alert_complaint'), models.Index(fields=['violation'], name='idx_vee_alert_violation'), models.Index(fields=['service_slug'], name='idx_vee_alert_service'), models.Index(fields=['generated_at'], name='idx_vee_alert_date'), models.Index(fields=['route_type', 'route_id'], name='idx_vee_alert_route')],
            },
        ),
    ]
