# Generated by Django 6.0.3 on 2026-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veeduria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección textual opcional para refinar la ubicación (calle, número, referencia).', max_length=300),
        ),
    ]
