# Generated by Django 6.0.3 on 2026-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veeduria', '0002_add_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='custom_aspect_description',
            field=models.CharField(blank=True, help_text='Descripción del problema cuando aspect_slug="other-issue".', max_length=200),
        ),
    ]
