# Generated by Django 6.0.3 on 2026-05-26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veeduria', '0003_add_custom_aspect_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='internal_notes',
            field=models.TextField(
                blank=True,
                help_text='Notas internas del veedor/coordinador. No visibles para el ciudadano.',
            ),
        ),
        migrations.AddField(
            model_name='complaint',
            name='severity',
            field=models.CharField(
                choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')],
                default='medium',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(
                choices=[
                    ('received', 'Recibida'),
                    ('triaged', 'Caracterizada'),
                    ('in_field', 'En verificación de campo'),
                    ('escalated', 'Escalada a entidad'),
                    ('resolved', 'Resuelta'),
                    ('rejected', 'Rechazada / improcedente'),
                ],
                default='received',
                max_length=20,
            ),
        ),
    ]
