# Generated by Django 6.0.3 on 2026-05-26
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veeduria', '0005_migrate_legacy_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_full_name', models.CharField(blank=True, max_length=200)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='complaint_status_events',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('complaint', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='status_events',
                    to='veeduria.complaint',
                )),
            ],
            options={
                'verbose_name': 'Evento de cambio de estado',
                'verbose_name_plural': 'Eventos de cambio de estado',
                'db_table': 'vee_complaint_status_event',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['complaint'], name='idx_vee_evt_complaint'),
                    models.Index(fields=['created_at'], name='idx_vee_evt_created'),
                ],
            },
        ),
    ]
