# Generated by Django 6.0.3 on 2026-04-28 19:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='ID compuesto por capa fuente (10001+, 20001+, ...)', unique=True)),
                ('name', models.CharField(max_length=300)),
                ('space_type', models.CharField(choices=[('park', 'Parque público'), ('road_divider', 'Separador vial'), ('corridor', 'Corredor verde'), ('node', 'Nodo de espacio público'), ('sports', 'Polideportivo'), ('other', 'Otro')], default='other', max_length=20)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Área en m² calculada en EPSG:3116', max_digits=12, null=True)),
                ('source_layer', models.CharField(blank=True, help_text='Capa POT de origen. Ej: U19_EP3, SEPARADOR', max_length=50)),
                ('neighborhood_id', models.IntegerField(blank=True, null=True)),
                ('neighborhood_name', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Espacio público',
                'verbose_name_plural': 'Espacios públicos',
                'db_table': 'geodata_public_space',
                'ordering': ['name'],
            },
        ),
    ]
