# Generated by Django 6.0.3 on 2026-04-29 00:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('area_hectares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'core_commune',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identificador estable. Ej: urbaser, vivienda, cultura', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nombre legal o público. Ej: Urbaser S.A. E.S.P.', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('app_label', models.CharField(blank=True, help_text='Django app label que registra el ServiceProvider de esta sección', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'core_section',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('osm_id', models.CharField(blank=True, max_length=50)),
                ('dane_code', models.CharField(blank=True, max_length=25)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neighborhoods', to='core.commune')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'core_neighborhood',
                'ordering': ['commune__number', 'name'],
            },
        ),
    ]
